services:
  api:
    image: application/api
    build:
      context: .
      dockerfile: Dockerfile.api
    command: sh -c "npm run migrate:deploy && npm run start:dev"
    stop_grace_period: 0s
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app

  db:
    image: application/db
    build:
      context: .
      dockerfile: Dockerfile.db
    stop_grace_period: 0s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./.postgres:/var/lib/postgresql/data
